### ISSUE TITLE
Fontfamily not activating in VSCode? 

### ISSUE THREAD

**Issue by PsySolix** [githubnext/monaspace#32] opened 2023-11-10 09:22 UTC
So I first followed the readme, for MACOSX & ran the bash file. 
Then verified if I have all the fonts in Font Book -> they are there. 

## Using the following options in VSCODE: 
`"editor.fontLigatures": true,`
`"editor.fontFamily": "Monaspace, Arial, serif",` // for testing

> Also tried with the Monaspace _____

## Result
Seeing Arial being used in the editor... Is there something that I'm missing? 

Thanks in advance!

**Comment by PsySolix** [comment] 2023-11-10 09:29
## Solution: 

Okay so for people having the same "oopsie" moment as me.. the _____ is the name of the variant of the package. So for VSCode you need: 

```
"editor.fontFamily": "'Monaspace Neon', serif", (or Argon or ...)
```

**Comment by roel4ez** [comment] 2023-11-10 11:03
FWIW, for me it only works by specifying the full Font name, e.g. `Monaspace Neon Var`
![image](https://github.com/githubnext/monaspace/assets/1822123/c13ab90f-efdf-4bdb-980f-da409d181873)

```json
"editor.fontFamily": "'Monaspace Neon Var', monospace"
```

**Comment by balupton** [comment] 2023-11-10 15:44
Yeah, I was thinking I would specify just `Monaspace` and then it would mix and match accordingly. Seems that is not the case: https://github.com/githubnext/monaspace/issues/6

**Comment by athompson-merlin** [comment] 2023-11-15 16:39
See one identified possible root cause at #111.

**Comment by idan** [comment] 2023-11-30 02:36
Whoops, GH auto closed this when I merged #125 

We'll produce a new build soon and check that this (and related issues) are solved.

**Comment by akselerando** [comment] 2023-12-15 11:57
Just wanted to add (in case someone else was stuck with the same problem as me), that the fonts only appeared in vscode for me after *closing* and *reopening* the window. Just hitting Ctlr+Shift+P and `Developer: reopen window` was not enough

**Comment by sujeewasandeepa** [comment] 2024-03-06 11:29
Do you guys know how to use different variants like 'medium' on VS Code. Using it like this 
`Monaspace Neon Var Medium` doesn't work.

**Comment by yvvt0379** [comment] 2024-03-08 06:27
Try adding this line to settings.json:
```json
"editor.fontWeight": "medium",
```

**Comment by heathercran** [comment] 2024-05-21 23:38
I'd recommend using the static Monaspace fonts in VS Code, as it doesn't fully support variable fonts yet. That should allow you to set the font weight as normal.

**Closed by heathercran** 2024-05-21 23:38 UTC
