### ISSUE TITLE
Monspace 1.1: VS Code prefers semiwide extralight for some reason

### ISSUE THREAD

**Issue by adiabatic** [githubnext/monaspace#205] opened 2024-05-04 06:45 UTC
I suppose an easy fix would be to remove the extrawide and semilight variants of the fonts, but…

This is what fonts look like on my laptop running Sonoma, in the latest version of VS Code:

![Monaspace 1.0](https://github.com/githubnext/monaspace/assets/101246/b64f4399-399f-4db2-9b0b-7aed2a8c4680)

And this is what I get on my desktop, with all the old versions of Monaspace removed and the new ones copied from the `otf` folder in 1.1:

![monaspace 1.1](https://github.com/githubnext/monaspace/assets/101246/bd18588e-e3e3-42fe-b4e7-d92b8ea98854)

Is there an obvious fix to this, other than by taking out the wider and thinner font variants? VS Code only seems to give me a way to control weight (`editor.fontWeight`), not the condensed/expanded axis.

**Comment by adiabatic** [comment] 2024-05-04 06:52
For what it's worth, the font selection is also widening the terminal font, even though the terminal font isn't on the thin side:

![Screenshot 2024-05-03 at 11 51 26 PM](https://github.com/githubnext/monaspace/assets/101246/aaa336b7-82d2-497d-81f3-9567970b0efa)

**Comment by adiabatic** [comment] 2024-05-04 07:37
If you want to select the too-thin and too-wide variants to disable them in macOS, you can do that with a couple of Smart Collections in Font Book:

![Monaspaces Light](https://github.com/githubnext/monaspace/assets/101246/8b8d7766-daa1-4d47-b570-e371108f6ff6)

![Monaspaces Wide](https://github.com/githubnext/monaspace/assets/101246/5278f5f1-fd3b-4aa9-97b8-549fd3414e05)

Then, right-click on each entry in the Collections area on the sidebar on the left and choose `Deactivate fonts in Monaspaces {Light,Wide}`.

**Comment by Finii** [comment] 2024-05-05 10:37
Well, the reason can be in the naming. Lets see what is set:

```console
$ fontforge ~/git/nerd-fonts/bin/scripts/name_parser/query_name MonaspaceKrypton-SemiWideLightItalic.otf
Examining 1 font files
======== MonaspaceKrypton-SemiWideLightItalic.otf ========
SFNT Fullname      ID 4     Monaspace Krypton SemiWide Light Italic
SFNT Family        ID 1     Monaspace Krypton SemiWide Light
SFNT SubFamily     ID 2     Italic
SFNT Pref Family   ID 16    Monaspace Krypton
SFNT Pref Styles   ID 17    SemiWide Light Italic
SFNT PS Name       ID 6     MonaspaceKrypton-SemiWideLightItalic
SFNT Compatible    ID 18    Monaspace Krypton SemiWide Light Italic
SFNT CID findfont  ID 20    -
SFNT WWS Family    ID 21    -
SFNT WWS SubFamily ID 22    -
PS fontname                 MonaspaceKrypton-SemiWideLightItalic
PS fullname                 Monaspace Krypton SemiWide Light Italic
PS familyname               Monaspace Krypton SemiWide Light
fondname                    None
```

Font grouping is done by
* ID 1 / 2 (classic RIBBI group, can only support `Regular`, `Italic`, `Bold`, and `BoldItalic`)
* ID 16 / 17 (expanded grouping)
* ID 21 / 22 (WWS grouping)

Some explanation is maybe in [1].

As we see above Monaspace has the Width in ID 17. That is usually not supported by application if I'm not mistaken.
Lots of fonts put the width axis instead into the Family (ID 16), which is then easier to select.

If they really want to support the widths axis the full WWS model should probably be used additionally.

[1] https://learn.microsoft.com/en-us/typography/opentype/spec/stat#alternate-font-family-models

**Comment by Finii** [comment] 2024-05-05 10:42
Counterexample, they put the width part (`Condensed` here) in ID16, that is supported more widely:

```
Examining 1 font files
======== NotoSans_Condensed-ExtraLightItalic.ttf ========
SFNT Fullname      ID 4     Noto Sans Condensed ExtraLight Italic
SFNT Family        ID 1     Noto Sans Condensed ExtraLight
SFNT SubFamily     ID 2     Italic
SFNT Pref Family   ID 16    Noto Sans Condensed
SFNT Pref Styles   ID 17    ExtraLight Italic
SFNT PS Name       ID 6     NotoSansCondensed-ExtraLightItalic
SFNT Compatible    ID 18    -
SFNT CID findfont  ID 20    -
SFNT WWS Family    ID 21    -
SFNT WWS SubFamily ID 22    -
PS fontname                 NotoSansCondensed-ExtraLightItalic
PS fullname                 Noto Sans Condensed ExtraLight Italic
PS familyname               Noto Sans Condensed ExtraLight
fondname                    None
```

(These comments are of course no solution for the problem per se, but should be a hint for the Monaspace team)

**Comment by kenmcd** [comment] 2024-05-05 23:48
> I suppose an easy fix would be to remove the extrawide and semilight variants of the fonts, but…
> 
> This is what fonts look like on my laptop running Sonoma, in the latest version of VS Code:
> 
> ![Monaspace 1.0](https://private-user-images.githubusercontent.com/101246/327929732-b64f4399-399f-4db2-9b0b-7aed2a8c4680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NDkxMDgsIm5iZiI6MTcxNDk0ODgwOCwicGF0aCI6Ii8xMDEyNDYvMzI3OTI5NzMyLWI2NGY0Mzk5LTM5OWYtNGRiMi05YjBiLTdhZWQyYThjNDY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQyMjQwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWFlMGYzMzI0NWIxYmI5MTEzYzljNTE4YTAwMzExZjc4ZWEzNWQwZTgxMzU1Njg4OWJlN2FhZjc3ZTNhN2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jysCbDfDIGBTRqRpH1A-xQVGxTDlTyCUjnvW005ILS4)
> 
> And this is what I get on my desktop, with all the old versions of Monaspace removed and the new ones copied from the `otf` folder in 1.1:
> 
> ![monaspace 1.1](https://private-user-images.githubusercontent.com/101246/327929838-bd18588e-e3e3-42fe-b4e7-d92b8ea98854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NDkxMDgsIm5iZiI6MTcxNDk0ODgwOCwicGF0aCI6Ii8xMDEyNDYvMzI3OTI5ODM4LWJkMTg1ODhlLWUzZTMtNDJmZS1iNGU3LWQ5MmI4ZWE5ODg1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQyMjQwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjUzNTIxNGZmN2JjNTY3Njc4N2NjOWFjMmMyYzlkMGFkNWYyN2QyODY2N2RmN2Y1ZGFkMDYxY2IyMmQwMDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g1dmgsnBsrSQ4cy4roPS9rWL4VqUbs9gShpd_sQx-AU)
> 
> Is there an obvious fix to this, other than by taking out the wider and thinner font variants? VS Code only seems to give me a way to control weight (`editor.fontWeight`), not the condensed/expanded axis.

Some of the fonts have the wrong `usWeightClass` setting in the OS2 table.
Monaspace Argon SemiWide ExtraLight is set to `400` which is the same as the Regular.
ExtraLight should be `300`.
ExtraBold is also set to `400`, and should be `800`.
Same in the other families - Krypton, etc.
The application is probably getting confused by multiple fonts all being set to `400`, and perhaps also name issues.
This will require the fonts being fixed before it has any chance of working properly.

**Comment by idan** [comment] 2024-05-06 16:40
Investigating!

**Comment by rileycran** [comment] 2024-05-06 17:35
Working on a fix for this, will update shortly! Thanks for spotting the metadata issue @Finii 🙏

**Comment by Finii** [comment] 2024-05-06 21:55
Good find @kenmcd !

In fact the Nerd Font patcher complains about the font:

```console
$ fontforge font-patcher --debug 2 monaspace-v1.100/fonts/otf/MonaspaceArgon-SemiWideExtraLight.otf 
Nerd Fonts Patcher v3.2.1-34 (4.14.3) (ff 20230101)
...
Done with Patch Sets, generating font...
WARNING: Possible problem with the weight metadata detected, check with --debug
DEBUG: Weight approximations: OS2/PS/Name: 400/400/200 (from 400/'Regular'/'ExtraLight')
...
```

(It was already the case with v1.000.)

Note that not only the OS2 weight is wrong, but also the PS weight, which all three should match somehow. Not that there are fixed rules how they all interact (*), but certainly you should not have the same weights for different weights ;-D

(*) There are some general agreements which number ranges match which weight names, but that is not fix and differs from font foundry to font foundry

What I commented on ... this is just my opinion.
And it directly contradicts the expectations voiced here:

* https://github.com/githubnext/monaspace/issues/111#issuecomment-2053775115

> There is some odd behavior with the semi-wide fonts showing up as a separate face

('Face' is probably used wrongly here, but it is clear what is meant.)

I usually prefer to have only all the weights on one selectable font family (group), and have the different widths (or whatever other axis there are) as different families, but as you see that varies.

Some `ttx` dump extracts:

![image](https://github.com/githubnext/monaspace/assets/16012374/3d145434-cdd2-461a-94dd-c485dec77469)

![image](https://github.com/githubnext/monaspace/assets/16012374/6004ba09-9f2b-44a3-a5b4-e9c565ff34e7)

![image](https://github.com/githubnext/monaspace/assets/16012374/5a91c79c-3706-4064-b35b-f2096d4530b5)

_(When I say "PS weight" I mean the weight name in the CFF table, see above)_

**Comment by Finii** [comment] 2024-05-06 22:18
No comment ;-)

NAME table copyright (SFNT) has been set but not "PS" copyright.

![image](https://github.com/githubnext/monaspace/assets/16012374/d89a03e1-ed61-46a1-997b-e91df98baeeb)

Hmm, and while I look there, was the goal not to have isFixedPitch set?
* #132

![image](https://github.com/githubnext/monaspace/assets/16012374/38ead30c-0ca2-4d38-8021-aa9c89cf6195)

**Comment by idan** [comment] 2024-05-09 19:07
Should be fixed in e6f6278955d3c47a77c1bdbf442f60838667cb98! Thank you for the report 🥰

**Closed by idan** 2024-05-09 19:07 UTC
Labels: bug

**Comment by floriancargoet** [comment] 2024-06-25 20:29
@idan This does not appear to be fixed for me. I'm using 1.101 and when I set VSCode's fontWeight to 300, the text is suddenly very wide.

![image](https://github.com/githubnext/monaspace/assets/110431/371ddc0c-2c3e-41da-9654-b43347db0baa)
![image](https://github.com/githubnext/monaspace/assets/110431/3dd41322-5c82-4376-81ee-f53edc159020)
![image](https://github.com/githubnext/monaspace/assets/110431/0e7181cd-4c61-43d8-b061-5fdd3d2c650e)

**Comment by rileycran** [comment] 2024-06-25 20:31
@floriancargoet This is inline with an unexpected behavior that @idan and I noted recently, not entirely sure what is causing it but we're investigating. It seems to have something to do with VSCode being unsure of which 300 weight font to use, from the family (which width, in other words).

**Comment by floriancargoet** [comment] 2024-06-25 20:34
Thank you for these details. Is there an issue I could subscribe to?

**Comment by rileycran** [comment] 2024-06-25 20:39
@floriancargoet Also, can you please use the Monaspace private use unicode glyph () into your editor, to confirm you're seeing the correct fonts, and not a caching issue?

**Comment by floriancargoet** [comment] 2024-06-25 20:40
It displays v1.101.

**Comment by kenmcd** [comment] 2024-06-26 00:20
> @idan This does not appear to be fixed for me. I'm using 1.101 and when I set VSCode's fontWeight to 300, the text is suddenly very wide.
> 

I don't think you should use a weight setting with the static fonts.
Set the Font Family to: `'Monaspace Neon Light',`
And set the Font Weight back to: `normal`
This appears to work for the normal text.

Or set the Font Family to the name of the variable font, 
and then set the Font Weight (my guess).
How this interacts with the Font Variations is unknown
because there is no docs (that I could find).

Not sure how that affects the Bold and Italic text.
I think it (vscode) assumes you are going to have a normal RIBBI family.
But in your case there is not a style-linked "bold" font.
And I think I have seen a way to set the Bold and the Italic manually.
Maybe it is all handled in the CSS.
Dunno. Their documentation is lacking.

**Comment by floriancargoet** [comment] 2024-06-26 09:54
There's a lot I don't understand in your comment (I know very little about the technical details of fonts) but I've set the VSCode font to 'Monaspace Neon Light', with the default weight and it displays correctly.

**Comment by kenmcd** [comment] 2024-06-27 01:46
> There's a lot I don't understand in your comment (I know very little about the technical details of fonts) but I've set the VSCode font to 'Monaspace Neon Light', with the default weight and it displays correctly. Thanks.

After looking at this a bit more it appears VSCode does need a standard Regular/Italic/Bold/BoldItalic font family to work as expected.
Depending on the code language and the theme used, some code blocks will be Bold and some will be Italic. 
So the style-linking matters.
Your Light is not linked to a "bold" which it can select.
VSCode apparently does create fake bold and fake italic when they do not exist for that RIBBI group.
So you are probably getting a fake bold.
You can tell because the fake Bold is probably wider than the Regular (or Light in your case).
Take a look and see if you have that happening.

The same thing happened with another font family, but with Notepad++.
The user wanted to use Light and Medium.
Just style-linking those (as Regular and Bold) did not work.
I had to actually change the Light to Regular, and the Medium to Bold, and the same for the Italics, and made a new RIBBI four font set.
That worked in Notepad++.
We may have to do the same thing here.

So be aware and note if you see fake bold or fake italic.
