### ISSUE TITLE
These fonts are unusable in modern IDEs and editors.

### ISSUE THREAD

**Issue by zd-dalibor** [githubnext/monaspace#111] opened 2023-11-14 14:27 UTC
Hi,
Thanks for this grate work, but this is not usable at all.

1. It is not recognized as monospace font by modern IDEs like IntelliJ and Visual Studio. Only VS Code is working fine with these fonts.
2. Under windows is not visible by IDEs if it is not installed for **all users**, most developers working in controlled environments where using **admin privileges** is denied and installing fonts for **all users** requires **admin rights**
3. It is not rendering correctly in windows terminal, also it is not recognized as monospace fonts in windows terminal (for other terminal emulators I do not know)
4. There is no Nerd Font version (I do not know if this font is possible to be patched with nerd-font patcher), so it is not usable for all variants of **oh-my-...** and for Neovim

**Comment by atomicbird** [comment] 2023-11-14 17:50
This seems to be a platform-specific issue, because macOS recognizes the fonts as fixed width, and they can be used in Xcode and other developer tools.

**Comment by jbehrens94** [comment] 2023-11-14 20:47
They can be used with Xcode, but as mentioned in issue #23 most of the fancy font features don't work.

**Comment by garthk** [comment] 2023-11-14 23:40
@jbehrens94 have you dug around the typography settings? I found them helpful in Monterey, where they even showed the texture healing as an option by name. Ventura, less so, but I'll post some screen shots so people know where to look after they open the Fonts dialog:

<img width="366.5" height="241.5" alt="Font dialog with midline ellipsis in circle (⋯) button highlighted" src="https://github.com/githubnext/monaspace/assets/15906/2d1ce1fb-d993-49ac-86e6-1a275579cc93">
<img width="90" height="121" alt="Menu with Typography… option highlighted" src="https://github.com/githubnext/monaspace/assets/15906/bac48976-48ce-4e1f-bcfb-d3a75b923d0c">
<img width="153" height="321" alt="Typography dialog" src="https://github.com/githubnext/monaspace/assets/15906/a5ad4e1b-3f6d-43bc-b45e-30a4330017a4">

These work in Terminal.app. I have not checked them in XCode.app.

**Comment by atomicbird** [comment] 2023-11-15 00:10
@garthk They don't work in Xcode. You can open and change typography settings but @jbehrens94 is correct, they have no effect.

**Comment by athompson-merlin** [comment] 2023-11-15 16:38
I have to agree - these fonts, as-is, are nearly useless on Windows.  Only those very few applications that have a convenient configuration file AND are willing to use variable-pitch fonts (iow: VS Code and very little else) can use Monaspace; everything else doesn't recognize it as a valid monospace font.

The PANOSE "Proportion" field in all the fonts is currently unset (or set to "Any", same net effect) whereas it needs to be set to "Monospace" to be visible in most editors/terminal emulators.

I'm unsure how to change this in the Monaspace build, but in FontForge at least, the setting can be found at Element->Font Info->OS/2->Panose->Proportion.  I'm just not willing to manually edit 100+ files...

**Comment by athompson-merlin** [comment] 2023-11-15 16:40
Ah, someone beat me to it, on #17.

**Comment by Finii** [comment] 2023-11-16 06:12
Nerd Font automatically fixes the Panose flags on patching. The patched font seems to be working on Windows, at least it shows.

Resources:
* https://github.com/ryanoasis/nerd-fonts/pull/1405
* To try out: [MonispaceNeonNerdFont.tar.xz.gz](https://github.com/githubnext/monaspace/files/13372947/MonispaceNeonNerdFont.tar.xz.gz)

The results on Windows are kind of mixed. While it shows in bold (i.e. `monospaced`) in Visual Studio it does not in Windows Terminal.

Maybe you can try things out and report.

Screenshots: (come in a minute)

**Comment by zd-dalibor** [comment] 2023-11-16 07:07
Hi @Finii 

The patched font is visible in windows terminal.

In IntelliJ ligatures are missing, and it is only visible if it is installed for all users (required admin rights). I think this is because it is OTF type. It will be nice if we can get TTF type version for windows, this will work for current user install.

The other font wights are missing (Extra Light, Light, Semi Light, Medium, Semi Bold...).

Also, other flavors are missing (Argon, Xenon, Radon, Krypton). This is only Neon.

<img width="758" alt="image" src="https://github.com/githubnext/monaspace/assets/226822/2c7cd9c4-e374-40ea-953f-5cd944498c50">

**Comment by Finii** [comment] 2023-11-16 08:19
@zd-dalibor 

Well, for Nerd Fonts you just need to add `--ext ttf` to get a ttf font out of the patcher. But the problem is the hints. Postscript fonts (`.otf`) have far less advanced hinting, just by 'blue zones', while Truetype fonts (`.ttf`) use instructions that can differ glyph by glyph. There is no way to automatically convert otf to ttf hints and it is impossible to convert ttf to otf hints at all.

So usually you need to stay in the realm that the original font manufacturer choose, because the look will be different (in small details).

As font designer I also would not want to support both, because usually the look will be different.
But I would choose ttf over otf nowadays, because specifically of the hinting. Both (ttf and otf) are OpenType fonts and the other capabilities are comparable.

Some weights I did not include [1] in the Nerd Font set, because I deemed them 'not useful' for terminal use. But Medium is there:

![image](https://github.com/githubnext/monaspace/assets/16012374/c55f93c6-1471-40fc-a3ad-afe579d253f9)

If you think other weights are useful, let me know. I just want to limit the number of sub-fonts in Nerd Fonts.

> Also, other flavors are missing (Argon, Xenon, Radon, Krypton). This is only Neon.

Correct. I just put one style here, as that should be sufficient to check if this threads problem (not usable in IDEs) would be fixed with the Nerd Fonts versions, because then we specifically know what needs to change in the original (this repo's) font to make them work. The Nerd Fonts patcher tells users what quirks it fixes in to-be-patched fonts to make them usable ;-)

For example, as mentioned already in a lot places:

```console
$ fontforge font-patcher --debug 2 --dry src/unpatched-fonts/Monaspace/Krypton/MonaspaceKrypton-MediumItalic.otf --makegroups 4
Nerd Fonts Patcher v3.0.2-167 (4.7.1) (ff 20230101)
DEBUG: Naming mode 4
DEBUG: Monospace check: Panose is invalid ([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]); glyph-width-mono True
INFO: Setting Panose 'Family Kind' to 'Latin Text and Display' (was 'Any')
INFO: Setting Panose 'Proportion' to 'Monospaced' (was 'Any')
INFO: Redistributing line gap of 400 (200 top and 200 bottom)
DEBUG: Extended glyphs wider bounding box than basic glyphs
DEBUG: Font has negative right side bearing in extended glyphs
DEBUG: Final font cell dimensions 1240 w x 2400 h
...
```

So the aim here was not to provide people with a Nerd Fonts version but to help Githubnext fix bugs.

[1] https://github.com/ryanoasis/nerd-fonts/pull/1405/commits/05c751441d9be98bab3ad9f9f4c49a25be496338

**Comment by zd-dalibor** [comment] 2023-11-16 12:07
Hi @Finii thanks for the response.

For me the normal/400 weight is too thick for my taste, it will be nice that patched fonts keep all weights from original font. But this is only my opinion. Nevertheless, nerd font patcher is available to everyone, so anyone can build their own version.

**Comment by zd-dalibor** [comment] 2023-11-17 17:52
@Finii ,

I am using docker nerd font patcher image to quickly patch all fonts in the folder:

```bash
docker run --rm -v /path/to/fonts:/in:Z -v /path/for/output:/out:Z nerdfonts/patcher [OPTIONS]
```

Maybe, I can use `--name` option to create separately Regular, Italic, Bold and Bold Italic from specific originals font I want. But, maybe I am wrong, because the font patcher always appends internal font weight to the name of patched font. But again, this will require to patch each font separately.

It will be nice if you can share some easy way for this. Some applications, especially on windows, does not understand these in the middle font weights.

**Comment by Finii** [comment] 2023-11-17 18:42
> share some easy way for this

There is a new feature in `font-patcher` since [this commit](https://github.com/ryanoasis/nerd-fonts/commit/178cda06291051d6bd6dcf2bb5525cd82874de36)
Make sure you have the latest docker image.
The in-parens version of the patcher needs to be >= 4.7.0

* Create additional directory for example `my_dir`, that will be later used for `-v ..."/in`
* Rename the fonts on copying into `my_dir`:
  * `MonaspaceNeon-Thin.otf` -> MonaspaceNeon-Regular.otf`
  * `MonaspaceNeon-ThinItalic.otf` -> MonaspaceNeon-Italic.otf`
  * `MonaspaceNeon-Light.otf` -> MonaspaceNeon-Bold.otf`
  * `MonaspaceNeon-LightItalic.otf` -> MonaspaceNeon-BoldItalic.otf`
* Instruct `font-patcher` to detect the font name/weight/style based on **filename** instead of internal data
  Add `--name filename`
* I have not tested that, but `font-patcher` usually 'heals' source fonts, so that now it will set all the needed flags for the patched fonts to be detected as RIBBI set.
* Of course you can give the patched font _any_ name, so maybe this is more reasonable:
  `MonaspecialNeon-Regular.otf` etc, so that you can distinguish it from the 'original' NF

[1] https://github.com/ryanoasis/nerd-fonts/wiki/ScriptOptions

**Comment by HunterZ** [comment] 2023-11-17 18:48
Installed the TTF flavors from release version 1.000 in Windows 11, and there are a number of immediate issues trying to use them with Terminal:
- do not appear in the list of monospace fonts; need to enable "show all fonts" which then results in a warning
- fonts are rendered in italics for some reason, and Terminal does not provide a way to select this (only weights)

Seems like Windows support just didn't get much attention, which is ironic.

**Comment by Finii** [comment] 2023-11-17 18:54
> fonts are rendered in italics for some reason

I guess this is #117. Maybe try the static versions.

**Comment by HunterZ** [comment] 2023-11-18 18:53
Seems like that would sacrifice a lot of the novelty of these fonts though.

**Comment by Finii** [comment] 2023-11-18 18:59
@HunterZ That Monaspace is a variable font is the novelty for you? :thinking: I thought VF is the new normal :grimacing: 
For me the novelty is the texture healing - and as that works via `calt` is also possible in static fonts.
Maybe misunderstanding?

**Comment by idan** [comment] 2023-11-30 02:36
Whoops, GH auto closed this when I merged #125 

We'll produce a new build soon and check that this (and related issues) are solved.

**Comment by Ryuuji159** [comment] 2023-12-18 13:14
Apparently the font still has this issue, it doesnt really work with gnome terminal (not detected) or any jetbrains ide (no ligatures or texture healing), when will a build be made with that fixed?

**Comment by zd-dalibor** [comment] 2023-12-18 14:30
Hi, there is only two issues here for me:

1. Applications do not detect these as a monospace fonts
2. Jetbrains IDE detect these fonts under windows only if they are installed for all users (but this is not the case with other fonts e.g. Cascadia - you can install Cascadia for current use and Jetbrains IDEs will detect it)

All other features like ligatures, texture healing, variable width... are specific open font standard features, which are relatively new, are only supported with small number of editors and terminals (I think under windows those features are fully supported in vscode and wizterm, but need to be explicitly enabled, e.g. for vscode `"editor.fontLigatures": "'ss02' on"`, other application will ignore those features).

In general, those open type standard features only work for web-based rendering engines, native apps still do not support them (maybe because need to be implemented on OS level). And by me, this is disappointing because this gives advantage to electron-like instead of native applications.

**Comment by Finii** [comment] 2023-12-18 17:08
> All other features like ligatures, texture healing, variable width... are specific open type font standard features, which are relatively new

While "texture healing" is a novel concept it uses the very old contextual alternatives `calt` iirc. A lot programming fonts have these since ... at least 2010 I guess. Like `Fira Code`s arrays for example. `calt` is supported in almost all terminals if I'm not mistaken.

I believe we have found out why the font is not detected by `Gnome Terminal`, but the actual fixing will probably take some time.
Meanwhile you could check if the `Nerd Font Mono` (`NFM`) variants in https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Monaspace.tar.xz do work as you expect, because some issues are autocorrected there.

Maybe you can try `MonaspiceNe NFM Regular` or some other `NFM` and report back, that would help finding the underlying issue.

Why JetBrains does not show the "texture healing" is beyond me. This is technically no "advanced" feature like ligatures or variable fonts.

With this electron versus 'native', I have no clue, I work only in terminals with real native (i.e. textmode) applications :-D

**Comment by Finii** [comment] 2023-12-18 17:15
> but need to be explicitly enabled, e.g. for vscode "editor.fontLigatures": "'ss02' on"

If you like a stylistic set (for example SS02: Special rendering of <= and >=) and your IDE does not support stylistic sets, I believe you can just "turn it on as default" in the font file with for example https://github.com/MuTsunTsai/fontfreeze.

**Comment by Ryuuji159** [comment] 2023-12-18 17:28
Thanks, the NFM version works on gnome terminal, but on jetbrains, it still doesnt work properly, I can't really be sure if texture healing is working, but ligatures definitely aren't
![image](https://github.com/githubnext/monaspace/assets/17039188/51ae7063-db19-4ed4-8b2b-0fb402548b46)

It shouldn't be a problem with jetbrains because it works with other fonts, like Fira Code
![image](https://github.com/githubnext/monaspace/assets/17039188/da631c1c-d5a2-4500-b384-49612efe0aba)

**Comment by Finii** [comment] 2023-12-18 17:40
Thanks for reporting back!

Ligatures are indeed a problem as I pointed out in https://github.com/githubnext/monaspace/issues/132.
The reason is that the ligatures here are really ligatures, while other font's ligatures are not technically ligatures but contextual alternatives. This can not be easily changed but needs a lot of manual editing. I do not know why Githubnext implemented the ligatures as ligatures, though.

But that the NFM works in principle is good, because a) Nerd Fonts' fonts work, which is my responsibility, and b) all necessary steps of change here at Monaspace are already layed out (I mentioned them in for example 132). I mentioned all I know of, which is all that Nerd Font does, which seems to be sufficient ;-)

**Comment by Finii** [comment] 2023-12-18 22:10
This is from your upper image...

Texture healing is active, at least in the preview on your image's right side.

To make this more obvious I copied `ini` from the word `maximize` and put it just below `pme` or `development`.
Very visible the wider `m` next to two small `i` and a smaller `m` next to non-small `p` and `e`.

Also look at the word `maximize` itself in the first row, the `m` next to the `a` is smaller than the `m` next to the `i` within that one word.

So it does work (as expected ;-)
Ligs are a different thing, maybe. But the technology behind texture healing is very old, but noone ever came up with this concept of texture healing (as far as I know).

![Screenshot 2023-12-18 at 22 59 40](https://github.com/githubnext/monaspace/assets/16012374/c04a540b-4097-4669-b6a8-0f5fa7ec5d63)

**Comment by Nargonath** [comment] 2024-01-11 19:27
I just discovered Monaspace and as many other I'm excited to give it a try but to discover that the ecosystem might not have caught up yet to use it properly. Seeing all issues open asking to help use it or people saying it doesn't work in "X", what do you think of improving the support section in the README to list the support in various terminals or other IDE so we know were it stands at a glance?

**Comment by mrclayman** [comment] 2024-01-14 15:32
> Whoops, GH auto closed this when I merged #125
> 
> We'll produce a new build soon and check that this (and related issues) are solved.

Hi @idan , any ETA on the new version? Cheers. :blush:

**Comment by ThePyroTF2** [comment] 2024-01-19 04:24
What's the status on the font being recognized as monospaced? Right now, I can't use this font with the Kitty terminal because it is an absolute requirement that the font be recognizable as monospaced.

**Comment by ThePyroTF2** [comment] 2024-01-19 04:28
Wait a minute, that's what #125 is about! :facepalm:
Nevermind. Unfortunate that such a crucial feature isn't on release yet, but I can handle cloning + building.

**Comment by Cremesis** [comment] 2024-02-12 10:53
Waiting for the new release!

**Comment by HunterZ** [comment] 2024-02-23 23:24
> Whoops, GH auto closed this when I merged #125
> 
> We'll produce a new build soon and check that this (and related issues) are solved.

3 months later, and this project is looking kind of abandoned. Oh well :(

**Comment by jbehrens94** [comment] 2024-02-24 14:07
It's still not fixed and it's really sad, I would've hoped that GitHub would be more professional and responsible than this.

**Comment by mrclayman** [comment] 2024-02-29 07:56
Has this really been abandoned? :confused: I mean, the radio silence is not exactly reassuring but I'm still hoping that they are just fixing all of the issues reported. Can @idan or somebody else from the GH team shed some light on this?

**Comment by equinox-and-solstice** [comment] 2024-04-13 21:49
> Has this really been abandoned? 😕 I mean, the radio silence is not exactly reassuring but I'm still hoping that they are just fixing all of the issues reported. Can @idan or somebody else from the GH team shed some light on this?

There have been no updates to any registered branches in five months. This thing is toast

**Comment by equinox-and-solstice** [comment] 2024-04-13 22:11
However, I installed the 42 individual fonts for the two faces that I liked in particular, and that almost worked out? There is some odd behavior with the semi-wide fonts showing up as a separate face, but... not as odd as some of my code in Eclipse:

![wild parentheses](https://github.com/githubnext/monaspace/assets/10746223/3f9de42f-c164-4274-83df-321ef3e725b6)
![crazy number placement and @Test attribute](https://github.com/githubnext/monaspace/assets/10746223/37c1bcd5-28c6-4bb6-a7f1-1fb000f7e933)

**Comment by idan** [comment] 2024-04-14 02:05
Not toast! Work is happening, just not in the public eye. Stay tuned, I know it's frustrating!

**Comment by justDeeevin** [comment] 2024-04-14 03:04
Thanks for the reassurance. I look forward to whatever you have cooking.

**Comment by mrclayman** [comment] 2024-05-05 17:47
I am really happy to see I was wrong. Huge thanks to all at Github and Lettermatic for the update. It's awesome to see that this typeface is still being worked on and improved.

**Comment by kenmcd** [comment] 2024-05-05 20:21
> However, I installed the 42 individual fonts for the two faces that I liked in particular, and that almost worked out? There is some odd behavior with the semi-wide fonts showing up as a separate face: ![font selections](https://private-user-images.githubusercontent.com/10746223/322233514-eb1e0a48-aaea-4513-9a5e-085c525be0db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MzMzMzMsIm5iZiI6MTcxNDkzMzAzMywicGF0aCI6Ii8xMDc0NjIyMy8zMjIyMzM1MTQtZWIxZTBhNDgtYWFlYS00NTEzLTlhNWUtMDg1YzUyNWJlMGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE4MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNTE1OWI2ZDEwNjI2MWIwZTdkM2VlZjM2Y2FmZDQwYjZiNWIxMjc1ZTg5YWZiYjI0MDNmNTg5OGFjMGY0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIuGLBSPWM0xcmyfwhK8SYnNDhF_HUE0dyGX3Qy6JUo)
> 
> But... not as odd as some of my code in Eclipse...

Is your screenshot from Eclipse?
And on what operating system?

In the new v1.100 release there are still name issues and settings which will certainly cause problems in Windows applications (e.g. LibreOffice, Word, etc.) and may also affect some of the code editors. So I am trying get a bit more info to be able to test potential solutions, and then post a bug here.
Or it may just require making a LibreOffice/Windows-friendly version.
Because it is _not_ going to work like this.

**Comment by equinox-and-solstice** [comment] 2024-05-05 20:46
> Is your screenshot from Eclipse? And on what operating system?

Yup, these are from Eclipse 2024-03 on Windows 11 Home version 10.0.22631.

**Comment by kenmcd** [comment] 2024-05-05 21:12
> > Is your screenshot from Eclipse? And on what operating system?
> 
> Yup, these are from Eclipse 2024-03 on Windows 11 Home version 10.0.22631.

OK. Thanks.

**Comment by heathercran** [comment] 2024-05-21 22:39
Panose flags were fixed in version 1.1, which will resolve a lot of the issues in this thread regarding programs not recognizing the fonts. The 1.2 update will also include static fonts with all ligatures enabled by default, which will make the fonts compatible with programs that do not support enabling stylistic sets, like IntelliJ IDEA.

**Comment by Karmalakas** [comment] 2024-06-07 13:07
Not sure how much this is related, but I didn't mange to make it work on PHP Storm. Tried installing both OTF and TTF versions. IDE just wouldn't pick up the fonts. While searching, I found multiple posts saying, that for IntelliJ to pick up fonts, they need to have at least 4 versions:
- Bold
- Italic
- BoldItalic
- Normal

I noticed, _Normal_ is not in the package, but _Regular_ is. Could this be the reason? Or is it still something that was discussed here? I tried latest v1.101

**Comment by Finii** [comment] 2024-06-07 17:30
> _Edit:_ Ah.. Installed for all users and fonts appeared. Still no ligatures, but that's another issue

Maybe https://github.com/githubnext/monaspace/issues/111#issuecomment-1813979425 helps?

**Comment by Karmalakas** [comment] 2024-06-07 20:35
I'm on IntelliJ and ligatures are enabled. Unless I'm missing something more.

**Comment by Noctumsempra** [comment] 2024-06-30 10:00
Hello, I'm using Jetbrains IDE (PHPStorm) and can't see ANY of the LOTs of Monaspace fonts I installed. They aren't listed at ALL in the IDE. Neither monospace nor proportional. No monaspace font is listed in my IDE.

ANy news on this? Any new release with this fix is planned or anything? Thanks in advance.

**Comment by idan** [comment] 2024-12-20 21:12
Closing this as a dupe of #20

**Closed** 2024-12-20 21:12 UTC
