### ISSUE TITLE
Sequential characters representing the same base letter must be of identical width

### ISSUE THREAD

**Issue by alllex** [githubnext/monaspace#74] opened 2023-11-11 20:46 UTC
One of the examples on the main page uses the word "plummier" to showcase Monaspace Neon.
There it's clearly visible that two letters "mm" look different when rendered next to each other.

<img width="309" alt="image" src="https://github.com/githubnext/monaspace/assets/2759152/67846fce-b13f-463c-8451-715fb8265c09">

This seems to be reproducible with all other fonts in the family.

Such rendering makes my eyes stumble when reading, which defeats the purpose of texture healing in this case.

Is this rendering intentional? Should an extra contextual rule be added to treat same sequential characters specially to make sure they are rendered identically?

**Comment by Logo121** [comment] 2023-11-12 22:22
See #42

**Comment by Krzysztof-Cieslak** [comment] 2023-11-14 11:27
Closing as duplicate of #42

**Closed** 2023-11-14 11:28 UTC
Labels: duplicate
