### ISSUE TITLE
First character of URLs are slashed through

### ISSUE THREAD

**Issue by parkerbxyz** [githubnext/monaspace#191] opened 2024-02-17 02:06 UTC
The first character of most URLs ends up with a slash through it when ligatures are enabled:

<img src="https://github.com/githubnext/monaspace/assets/17183625/c18255bb-73f5-49cd-ba7c-07eb7e377d8b" width="800px">

**Comment by kenmcd** [comment] 2024-02-17 18:20
The // discretionary ligature (`dlig`) is two characters wide (AW 2480)
and the application is treating it as one character wide (AW 1240).

**Comment by shuang886** [comment] 2024-02-29 05:24
Duplicate of https://github.com/githubnext/monaspace/issues/79 ?

**Comment by idan** [comment] 2024-05-03 23:56
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0

**Closed by idan** 2024-05-03 23:56 UTC
